/** Ideal adult weight ranges (kg) by breed and sex. Approximate breed-standard guidance. */
export type IdealWeightBounds = { min: number; max: number }
export type BreedIdealWeight = { female: IdealWeightBounds; male: IdealWeightBounds }

export const DOG_IDEAL_WEIGHTS: Record<string, BreedIdealWeight> = {
  "Afgánský chrt": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Aidi": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Airedale terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Akita": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Aljašský malamut": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Alpský jezevčíkovitý brakýř": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Americká akita": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Americký bezsrstý terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Americký buldok": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Americký foxhound": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Americký kokršpaněl": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Americký stafordširský terier": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Americký vodní španěl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Angl.-franc.honič de Petite Venerie": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Anglický buldok": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Anglický chrt (Greyhound)": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Anglický kokršpaněl": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Anglický mastif": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Anglický setr": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Anglický špringr španěl": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Anglický toy terier": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Appenzellský salašnický pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Ardenský bouvier": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Argentinská doga": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Ariégois": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Ariegský ohař krátkosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Artésko-normandský basset": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Artoisský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Australská kelpie": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Australský honácký pes": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Australský honácký pes s krátkým ocasem": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Australský ovčák": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Australský Silky terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Australský terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Auvergneský ohař krátkosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Azavak": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Barbet": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Barzoj - ruský chrt": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Basenji": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Basset Hound": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Bavorský barvář": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Beagle": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Beagle Harrier": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Bearded kolie": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Beauceron": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Bedlington terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Belgický grifonek": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Belgický ovčák": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Belgický ovčák - Groenendael": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Belgický ovčák - Laekenois": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Belgický ovčák - Malinois": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Belgický ovčák - Tervueren": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Bergamský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Bernský salašnický pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Biewer teriér": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Billy": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Bílý švýcarský ovčák": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Bišonek": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Black and Tan Coonhound": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Bloodhound": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Bobtail": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Boloňský psík": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Bordeauxská doga": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Border kolie": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Border terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Bosensko - hercegovinský - chorvatský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Bosenský hrubosrstý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Bostonský terier": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Bourbonský ohař krátkosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Brabantík": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Brazilská fila": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Brazilský buldok": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Brazilský terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Bretaňský ohař dlouhosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Briard": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Briquet Griffon Vendéen": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Bruselský grifonek": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Bullmastif": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Bulteriér": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Burgoský perdiquero": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Búrský buldok": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Cairn Terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Cao de Castro Laboreiro": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Cao de Serra de Aires": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Clumber španěl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Coton de Tuléar": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Curly Coated Retriever": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Černohorský planinský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Československý vlčák": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Český fousek": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Český horský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Český strakatý pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Český teriér": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Čínský chocholatý pes": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Čivava": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Čivava dlouhosrstá": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Čivava krátkosrstá": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Dalmatin": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Dandie Dinmont terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Dánská doga": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Dánsko-švédský farmářský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Dánský ohař krátkosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Deerhound": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Deltari Ilir": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Dlouhosrstý ohař z Pont-Audemer": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Dlouhosrstý vipet": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Dobrman": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Drentsche Patrisijshond": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Drever": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Dunker": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Entlebuchský salašnický pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Estrelský pastevecký pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Eurasier": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Faraónský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Field španěl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Finský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Finský špic": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Flanderský bouvier": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Flat Coated Retriever": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Foxhound": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Foxterier drsnosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Foxterier hladkosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Francouzský bílo-černý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Francouzský bílo-oranžový honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Francouzský buldoček": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Francouzský ohař dlouhosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Francouzský ohař krátkosrstý gaskoň.typu": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Francouzský ohař krátkosrstý pyren.typu": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Francouzský trikolorní honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Frízský ohař (Stabijhoun)": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Gaskoňsko-saintgeoiský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Gordonsetr": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Grónský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Haldenův honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Hamiltonův honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Hannoverský barvář": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Harrier": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Havanský psík": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Hokkaido": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Holandský ovčácký pudl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Holandský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Holandský pinč": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Hovawart": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Hrubosrstý modrý gaskoňský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Hygenův honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Chesapeake Bay Retriever": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Chien Fila de Saint Miguel": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Chinese Chongquing dog": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Chodský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Chortaja Borzaja": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Chorvatský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Chow chow": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Ibizský podenco": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Irish Glen of Imaal terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Irish Soft Coated Wheaten Terrier": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Irský červenobílý setr": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Irský setr": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Irský terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Irský vlkodav": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Irský vodní španěl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Islandský ovčácký pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Istrijský hrubosrstý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Istrijský krátkosrstý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Italský corso pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Italský drsnosrstý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Italský chrtík": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Italský krátkosrstý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Italský ohař": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Italský spinone": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Italský volpino": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Jack Russell Teriér": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Jaemthund": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Jakutská lajka": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Japan-chin": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Japonský špic": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Japonský terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Jezevčík": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Jihoruský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Kai": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Kanaánský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Kanadský eskymácký pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Kanárský podenco": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Kangalský pastevecký pes": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Karelský medvědí pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Katalánský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Kavalír King Charles španěl": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Kavkazský pastevecký pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Kerry blue terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "King Charles španěl": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Kintamani-Bali Dog": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Kishu": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Knírač malý": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Knírač střední": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Knírač velký": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Kolie dlouhosrstá": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Kolie krátkosrstá": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Komondor": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Kontinentální buldok": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Kooikerhondje": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Korejský Jindo Dog": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Korthalsův Griffon": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Krašský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Kromforländer": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Kuvasz": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Labradorský retriever": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Lagotto romagnolo": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Lakeland terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Lancashirský patař": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Landseer": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Lapinkoira": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Lapinporokoira": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Leonberger": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Lhasa Apso": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Louisianský leopardí pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Lvíček": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Maďarský chrt": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Maďarský ohař drátosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Maďarský ohař krátkosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Mali Medimurski pas - Medi": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Malorský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Maltézský psík": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Malý hrubosrstý vendéeský basset": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Malý kontinentální španěl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Malý modrý gaskoňský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Malý münsterlandský ohař": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Manchester terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Maremmansko-abruzský pastevecký pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Markiesje": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Mexický naháč": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Miniaturní americký ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Miniaturní bulteriér": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Modrý gaskoňský basset": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Modrý pikardský ohař dlouhosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Mops": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Moskevský strážní pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Mudi": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Neapolský mastin": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Německá doga": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Německý boxer": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Německý brakýř": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Německý křepelák": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Německý lovecký terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Německý ohař dlouhosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Německý ohař drátosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Německý ohař krátkosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Německý ohař ostnosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Německý ovčák": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Německý pinč": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Německý špic": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Německý špic malý": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Německý špic střední": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Německý špic trpasličí": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Německý špic velký": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Německý špic vlčí": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Nivernaisský hrubosrstý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Norbotenský špic": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Norfolk terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Norský buhund": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Norský losí pes černý": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Norský losí pes šedý": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Norský lundehund": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Norwich terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Nova Scotia Duck Tolling Retriever": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Novofundlandský pes": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Odis": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Opičí pinč": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Otterhound (Vydrař)": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Papillon": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Parson Russell Teriér": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Patterdale terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Pekingský palácový psík": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Perro de Presa Mallorquin": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Peruánský naháč": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Phaléne": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Pikardský ohař dlouhosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Pikardský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Plavý bretaňský basset": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Plavý bretaňský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Plott Hound": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Podhalaňský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Pointer": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Poitevin": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Polský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Polský chrt": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Polský lovecký španěl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Polský ogar": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Polský ovčák nížinný": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Porcelán": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Portugalský ohař": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Portugalský podengo": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Portugalský vodní pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Posávský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Pražský krysařík": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Presa Canario": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Pudl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Pudlpointr": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Puli": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Pumi": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Pyrenejský horský pes": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Pyrenejský mastin": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Pyrenejský ovčák s dl. srstí v obličeji": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Pyrenejský ovčák s kr.srstí v obličeji": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Rafeiro do Alentejo": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Rakouský krátkosrstý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Rakouský krátkosrstý pinč": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Redbone Coonhound": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Rhodéský ridgeback": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Rotvajler": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Rumunský karpatský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Rumunský mioritský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Rumunský ovčák - Bucovina": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Ruská barevná bolonka": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Ruskoevropská lajka": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Ruský černý terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Ruský toy": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Řecký honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Saarloosův vlčák": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Saint-Germainský ohař krátkosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Saluki - Perský chrt": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Samojed": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Sealyham terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Sedmihradský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Shar-Pei": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Sheltie": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Shiba": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Shih-tzu": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Shikoku": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Schillerův honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Sibiřský husky": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Sicilský chrt": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Skotský teriér": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Skye terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Sloughi": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Slovenský čuvač": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Slovenský kopov": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Slovenský ohař hrubosrstý": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Smalandský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Směs plemen": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Srbský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Srbský trikolorní honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Stafordšírský bullterier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Středoasijský pastevecký pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Sussex španěl": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Svatobernardský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Svatobernardský pes krátkosrstý": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Šarplaninský pastevecký pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Šiperka": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Španělský galgo": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Španělský mastin": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Španělský sabueso": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Španělský vodní pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Štýrský brakýř": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Švédský laponský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Švédský vallhund": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Švýcarský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Švýcarský nízkonohý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Taiwanský pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Tatranský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Thai Bangkaew dog": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Thajský ridgeback": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Tibetská doga": { female: { min: 40, max: 65 }, male: { min: 50, max: 80 } },
  "Tibetský španěl": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Tibetský terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Tosa-Inu": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Toy foxteriér": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Trpasličí pinč": { female: { min: 1.8, max: 3.5 }, male: { min: 2.2, max: 4.5 } },
  "Tyrolský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Uruguajský cimarron": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Valencian teriér": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Vel.franc.-anglický bílo-oranžový honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Vel.francouzsko-anglický trikolor.honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Velký franc.-anglický bílo-černý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Velký hrubosrstý vendéeský basset": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Velký modrý gaskoňský honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Velký münsterlandský ohař": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Velký švýcarský salašnický pes": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Velký vendéeský hrubosrstý honič": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Východoevropský ovčák": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Východosibiřská lajka": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Výmarský ohař": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
  "Welsh Corgi Cardigan": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Welsh Corgi Pembroke": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "Welsh terier": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Welššpringršpaněl": { female: { min: 9, max: 16 }, male: { min: 11, max: 20 } },
  "West Highland White Terrier": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Westfálský jezevčíkovitý honič": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Wetterhound": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Whippet": { female: { min: 5, max: 10 }, male: { min: 6, max: 12 } },
  "Yorkšírský terier": { female: { min: 14, max: 25 }, male: { min: 18, max: 32 } },
  "Západosibiřská lajka": { female: { min: 12, max: 22 }, male: { min: 15, max: 28 } },
  "Zlatý retriever": { female: { min: 16, max: 28 }, male: { min: 20, max: 35 } },
}

export const CAT_IDEAL_WEIGHTS: Record<string, BreedIdealWeight> = {
  "Americký curl dlouhosrstý": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Americký curl krátkosrstý": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Balinéská kočka": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Barmská kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Bengálská kočka": { female: { min: 4.5, max: 7.5 }, male: { min: 6, max: 10 } },
  "Birma": { female: { min: 4.5, max: 7.5 }, male: { min: 6, max: 10 } },
  "Bombay": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Britská dlouhosrstá kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Britská krátkosrstá kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Burmilla": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Cornish rex": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Devon rex": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Dlouhosrstá domácí kočka": { female: { min: 3, max: 5.5 }, male: { min: 4, max: 7 } },
  "Donský sphynx": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Egyptská mau": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Evropská kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Exotická kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "German rex": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Habešská kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Japonský bobtail krátkosrstý": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Kartouzská kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Korat": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Krátkosrstá domácí kočka": { female: { min: 3, max: 5.5 }, male: { min: 4, max: 7 } },
  "Kurilský bobtail dlouhosrstý": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Kurilský bobtail krátkosrstý": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Kymerská kočka": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "LaPerm dlouhosrstá": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "LaPerm krátkosrstá": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Lykoi": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Mainská kočka mývalí": { female: { min: 4.5, max: 7.5 }, male: { min: 6, max: 10 } },
  "Manská kočka": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Něvská maškaráda": { female: { min: 4.5, max: 7.5 }, male: { min: 6, max: 10 } },
  "Norská kočka lesní": { female: { min: 4.5, max: 7.5 }, male: { min: 6, max: 10 } },
  "Ocicat": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Orientální kočka dlouhosrstá": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Orientální kočka krátkosrstá": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Perská kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Peterbald": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Ragdoll": { female: { min: 4.5, max: 7.5 }, male: { min: 6, max: 10 } },
  "Ruská modrá kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Selkirk rex dlouhosrstý": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Selkirk rex krátkosrstý": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Siamská kočka": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Sibiřská kočka": { female: { min: 4.5, max: 7.5 }, male: { min: 6, max: 10 } },
  "Singapura": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Směs plemen": { female: { min: 3, max: 5.5 }, male: { min: 4, max: 7 } },
  "Snowshoe": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Sokoke": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Somálská kočka": { female: { min: 3.5, max: 5.5 }, male: { min: 4.5, max: 7.5 } },
  "Sphynx": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Thajská kočka": { female: { min: 2.5, max: 4 }, male: { min: 3.5, max: 5.5 } },
  "Turecká angora": { female: { min: 3.2, max: 5.5 }, male: { min: 4.2, max: 7 } },
  "Turecká van": { female: { min: 4.5, max: 7.5 }, male: { min: 6, max: 10 } },
}
