import type { PetType } from './petTypes'

export const DOG_BREEDS = [
  'Afgánský chrt',
  'Aidi',
  'Airedale terier',
  'Akita',
  'Aljašský malamut',
  'Alpský jezevčíkovitý brakýř',
  'Americká akita',
  'Americký bezsrstý terier',
  'Americký buldok',
  'Americký foxhound',
  'Americký kokršpaněl',
  'Americký stafordširský terier',
  'Americký vodní španěl',
  'Angl.-franc.honič de Petite Venerie',
  'Anglický buldok',
  'Anglický chrt (Greyhound)',
  'Anglický kokršpaněl',
  'Anglický mastif',
  'Anglický setr',
  'Anglický špringr španěl',
  'Anglický toy terier',
  'Appenzellský salašnický pes',
  'Ardenský bouvier',
  'Argentinská doga',
  'Ariégois',
  'Ariegský ohař krátkosrstý',
  'Artésko-normandský basset',
  'Artoisský honič',
  'Australská kelpie',
  'Australský honácký pes',
  'Australský honácký pes s krátkým ocasem',
  'Australský ovčák',
  'Australský Silky terier',
  'Australský terier',
  'Auvergneský ohař krátkosrstý',
  'Azavak',
  'Barbet',
  'Barzoj - ruský chrt',
  'Basenji',
  'Basset Hound',
  'Bavorský barvář',
  'Beagle',
  'Beagle Harrier',
  'Bearded kolie',
  'Beauceron',
  'Bedlington terier',
  'Belgický grifonek',
  'Belgický ovčák',
  'Belgický ovčák - Groenendael',
  'Belgický ovčák - Laekenois',
  'Belgický ovčák - Malinois',
  'Belgický ovčák - Tervueren',
  'Bergamský ovčák',
  'Bernský salašnický pes',
  'Biewer teriér',
  'Billy',
  'Bílý švýcarský ovčák',
  'Bišonek',
  'Black and Tan Coonhound',
  'Bloodhound',
  'Bobtail',
  'Boloňský psík',
  'Bordeauxská doga',
  'Border kolie',
  'Border terier',
  'Bosensko - hercegovinský - chorvatský ovčák',
  'Bosenský hrubosrstý honič',
  'Bostonský terier',
  'Bourbonský ohař krátkosrstý',
  'Brabantík',
  'Brazilská fila',
  'Brazilský buldok',
  'Brazilský terier',
  'Bretaňský ohař dlouhosrstý',
  'Briard',
  'Briquet Griffon Vendéen',
  'Bruselský grifonek',
  'Bullmastif',
  'Bulteriér',
  'Burgoský perdiquero',
  'Búrský buldok',
  'Cairn Terier',
  'Cao de Castro Laboreiro',
  'Cao de Serra de Aires',
  'Clumber španěl',
  'Coton de Tuléar',
  'Curly Coated Retriever',
  'Černohorský planinský honič',
  'Československý vlčák',
  'Český fousek',
  'Český horský pes',
  'Český strakatý pes',
  'Český teriér',
  'Čínský chocholatý pes',
  'Čivava',
  'Čivava dlouhosrstá',
  'Čivava krátkosrstá',
  'Dalmatin',
  'Dandie Dinmont terier',
  'Dánská doga',
  'Dánsko-švédský farmářský pes',
  'Dánský ohař krátkosrstý',
  'Deerhound',
  'Deltari Ilir',
  'Dlouhosrstý ohař z Pont-Audemer',
  'Dlouhosrstý vipet',
  'Dobrman',
  'Drentsche Patrisijshond',
  'Drever',
  'Dunker',
  'Entlebuchský salašnický pes',
  'Estrelský pastevecký pes',
  'Eurasier',
  'Faraónský pes',
  'Field španěl',
  'Finský honič',
  'Finský špic',
  'Flanderský bouvier',
  'Flat Coated Retriever',
  'Foxhound',
  'Foxterier drsnosrstý',
  'Foxterier hladkosrstý',
  'Francouzský bílo-černý honič',
  'Francouzský bílo-oranžový honič',
  'Francouzský buldoček',
  'Francouzský ohař dlouhosrstý',
  'Francouzský ohař krátkosrstý gaskoň.typu',
  'Francouzský ohař krátkosrstý pyren.typu',
  'Francouzský trikolorní honič',
  'Frízský ohař (Stabijhoun)',
  'Gaskoňsko-saintgeoiský honič',
  'Gordonsetr',
  'Grónský pes',
  'Haldenův honič',
  'Hamiltonův honič',
  'Hannoverský barvář',
  'Harrier',
  'Havanský psík',
  'Hokkaido',
  'Holandský ovčácký pudl',
  'Holandský ovčák',
  'Holandský pinč',
  'Hovawart',
  'Hrubosrstý modrý gaskoňský honič',
  'Hygenův honič',
  'Chesapeake Bay Retriever',
  'Chien Fila de Saint Miguel',
  'Chinese Chongquing dog',
  'Chodský pes',
  'Chortaja Borzaja',
  'Chorvatský ovčák',
  'Chow chow',
  'Ibizský podenco',
  'Irish Glen of Imaal terier',
  'Irish Soft Coated Wheaten Terrier',
  'Irský červenobílý setr',
  'Irský setr',
  'Irský terier',
  'Irský vlkodav',
  'Irský vodní španěl',
  'Islandský ovčácký pes',
  'Istrijský hrubosrstý honič',
  'Istrijský krátkosrstý honič',
  'Italský corso pes',
  'Italský drsnosrstý honič',
  'Italský chrtík',
  'Italský krátkosrstý honič',
  'Italský ohař',
  'Italský spinone',
  'Italský volpino',
  'Jack Russell Teriér',
  'Jaemthund',
  'Jakutská lajka',
  'Japan-chin',
  'Japonský špic',
  'Japonský terier',
  'Jezevčík',
  'Jihoruský ovčák',
  'Kai',
  'Kanaánský pes',
  'Kanadský eskymácký pes',
  'Kanárský podenco',
  'Kangalský pastevecký pes',
  'Karelský medvědí pes',
  'Katalánský ovčák',
  'Kavalír King Charles španěl',
  'Kavkazský pastevecký pes',
  'Kerry blue terier',
  'King Charles španěl',
  'Kintamani-Bali Dog',
  'Kishu',
  'Knírač malý',
  'Knírač střední',
  'Knírač velký',
  'Kolie dlouhosrstá',
  'Kolie krátkosrstá',
  'Komondor',
  'Kontinentální buldok',
  'Kooikerhondje',
  'Korejský Jindo Dog',
  'Korthalsův Griffon',
  'Krašský ovčák',
  'Kromforländer',
  'Kuvasz',
  'Labradorský retriever',
  'Lagotto romagnolo',
  'Lakeland terier',
  'Lancashirský patař',
  'Landseer',
  'Lapinkoira',
  'Lapinporokoira',
  'Leonberger',
  'Lhasa Apso',
  'Louisianský leopardí pes',
  'Lvíček',
  'Maďarský chrt',
  'Maďarský ohař drátosrstý',
  'Maďarský ohař krátkosrstý',
  'Mali Medimurski pas - Medi',
  'Malorský ovčák',
  'Maltézský psík',
  'Malý hrubosrstý vendéeský basset',
  'Malý kontinentální španěl',
  'Malý modrý gaskoňský honič',
  'Malý münsterlandský ohař',
  'Manchester terier',
  'Maremmansko-abruzský pastevecký pes',
  'Markiesje',
  'Mexický naháč',
  'Miniaturní americký ovčák',
  'Miniaturní bulteriér',
  'Modrý gaskoňský basset',
  'Modrý pikardský ohař dlouhosrstý',
  'Mops',
  'Moskevský strážní pes',
  'Mudi',
  'Neapolský mastin',
  'Německá doga',
  'Německý boxer',
  'Německý brakýř',
  'Německý křepelák',
  'Německý lovecký terier',
  'Německý ohař dlouhosrstý',
  'Německý ohař drátosrstý',
  'Německý ohař krátkosrstý',
  'Německý ohař ostnosrstý',
  'Německý ovčák',
  'Německý pinč',
  'Německý špic',
  'Německý špic malý',
  'Německý špic střední',
  'Německý špic trpasličí',
  'Německý špic velký',
  'Německý špic vlčí',
  'Nivernaisský hrubosrstý honič',
  'Norbotenský špic',
  'Norfolk terier',
  'Norský buhund',
  'Norský losí pes černý',
  'Norský losí pes šedý',
  'Norský lundehund',
  'Norwich terier',
  'Nova Scotia Duck Tolling Retriever',
  'Novofundlandský pes',
  'Odis',
  'Opičí pinč',
  'Otterhound (Vydrař)',
  'Papillon',
  'Parson Russell Teriér',
  'Patterdale terier',
  'Pekingský palácový psík',
  'Perro de Presa Mallorquin',
  'Peruánský naháč',
  'Phaléne',
  'Pikardský ohař dlouhosrstý',
  'Pikardský ovčák',
  'Plavý bretaňský basset',
  'Plavý bretaňský honič',
  'Plott Hound',
  'Podhalaňský ovčák',
  'Pointer',
  'Poitevin',
  'Polský honič',
  'Polský chrt',
  'Polský lovecký španěl',
  'Polský ogar',
  'Polský ovčák nížinný',
  'Porcelán',
  'Portugalský ohař',
  'Portugalský podengo',
  'Portugalský vodní pes',
  'Posávský honič',
  'Pražský krysařík',
  'Presa Canario',
  'Pudl',
  'Pudlpointr',
  'Puli',
  'Pumi',
  'Pyrenejský horský pes',
  'Pyrenejský mastin',
  'Pyrenejský ovčák s dl. srstí v obličeji',
  'Pyrenejský ovčák s kr.srstí v obličeji',
  'Rafeiro do Alentejo',
  'Rakouský krátkosrstý honič',
  'Rakouský krátkosrstý pinč',
  'Redbone Coonhound',
  'Rhodéský ridgeback',
  'Rotvajler',
  'Rumunský karpatský ovčák',
  'Rumunský mioritský ovčák',
  'Rumunský ovčák - Bucovina',
  'Ruská barevná bolonka',
  'Ruskoevropská lajka',
  'Ruský černý terier',
  'Ruský toy',
  'Řecký honič',
  'Saarloosův vlčák',
  'Saint-Germainský ohař krátkosrstý',
  'Saluki - Perský chrt',
  'Samojed',
  'Sealyham terier',
  'Sedmihradský honič',
  'Shar-Pei',
  'Sheltie',
  'Shiba',
  'Shih-tzu',
  'Shikoku',
  'Schillerův honič',
  'Sibiřský husky',
  'Sicilský chrt',
  'Skotský teriér',
  'Skye terier',
  'Sloughi',
  'Slovenský čuvač',
  'Slovenský kopov',
  'Slovenský ohař hrubosrstý',
  'Smalandský honič',
  'Směs plemen',
  'Srbský honič',
  'Srbský trikolorní honič',
  'Stafordšírský bullterier',
  'Středoasijský pastevecký pes',
  'Sussex španěl',
  'Svatobernardský pes',
  'Svatobernardský pes krátkosrstý',
  'Šarplaninský pastevecký pes',
  'Šiperka',
  'Španělský galgo',
  'Španělský mastin',
  'Španělský sabueso',
  'Španělský vodní pes',
  'Štýrský brakýř',
  'Švédský laponský pes',
  'Švédský vallhund',
  'Švýcarský honič',
  'Švýcarský nízkonohý honič',
  'Taiwanský pes',
  'Tatranský honič',
  'Thai Bangkaew dog',
  'Thajský ridgeback',
  'Tibetská doga',
  'Tibetský španěl',
  'Tibetský terier',
  'Tosa-Inu',
  'Toy foxteriér',
  'Trpasličí pinč',
  'Tyrolský honič',
  'Uruguajský cimarron',
  'Valencian teriér',
  'Vel.franc.-anglický bílo-oranžový honič',
  'Vel.francouzsko-anglický trikolor.honič',
  'Velký franc.-anglický bílo-černý honič',
  'Velký hrubosrstý vendéeský basset',
  'Velký modrý gaskoňský honič',
  'Velký münsterlandský ohař',
  'Velký švýcarský salašnický pes',
  'Velký vendéeský hrubosrstý honič',
  'Východoevropský ovčák',
  'Východosibiřská lajka',
  'Výmarský ohař',
  'Welsh Corgi Cardigan',
  'Welsh Corgi Pembroke',
  'Welsh terier',
  'Welššpringršpaněl',
  'West Highland White Terrier',
  'Westfálský jezevčíkovitý honič',
  'Wetterhound',
  'Whippet',
  'Yorkšírský terier',
  'Západosibiřská lajka',
  'Zlatý retriever',
] as const

export const CAT_BREEDS = [
  'Americký curl dlouhosrstý',
  'Americký curl krátkosrstý',
  'Balinéská kočka',
  'Barmská kočka',
  'Bengálská kočka',
  'Birma',
  'Bombay',
  'Britská dlouhosrstá kočka',
  'Britská krátkosrstá kočka',
  'Burmilla',
  'Cornish rex',
  'Devon rex',
  'Dlouhosrstá domácí kočka',
  'Donský sphynx',
  'Egyptská mau',
  'Evropská kočka',
  'Exotická kočka',
  'German rex',
  'Habešská kočka',
  'Japonský bobtail krátkosrstý',
  'Kartouzská kočka',
  'Korat',
  'Krátkosrstá domácí kočka',
  'Kurilský bobtail dlouhosrstý',
  'Kurilský bobtail krátkosrstý',
  'Kymerská kočka',
  'LaPerm dlouhosrstá',
  'LaPerm krátkosrstá',
  'Lykoi',
  'Mainská kočka mývalí',
  'Manská kočka',
  'Něvská maškaráda',
  'Norská kočka lesní',
  'Ocicat',
  'Orientální kočka dlouhosrstá',
  'Orientální kočka krátkosrstá',
  'Perská kočka',
  'Peterbald',
  'Ragdoll',
  'Ruská modrá kočka',
  'Selkirk rex dlouhosrstý',
  'Selkirk rex krátkosrstý',
  'Siamská kočka',
  'Sibiřská kočka',
  'Singapura',
  'Směs plemen',
  'Snowshoe',
  'Sokoke',
  'Somálská kočka',
  'Sphynx',
  'Thajská kočka',
  'Turecká angora',
  'Turecká van',
] as const

const ENGLISH_BREED_TO_CZECH: Record<string, string> = {
  'Golden Retriever': 'Zlatý retriever',
  'Labrador Retriever': 'Labradorský retriever',
  Labrador: 'Labradorský retriever',
  'Border Collie': 'Border kolie',
  'British Shorthair': 'Britská krátkosrstá kočka',
  'Maine Coon': 'Mainská kočka mývalí',
  Siamese: 'Siamská kočka',
  'Siberian Husky': 'Sibiřský husky',
  'French Bulldog': 'Francouzský buldoček',
  'German Shepherd': 'Německý ovčák',
}

export function localizeBreedName(breed: string): string {
  return ENGLISH_BREED_TO_CZECH[breed] ?? breed
}

export function getBreedsForType(type: PetType): readonly string[] {
  return type === 'dog' ? DOG_BREEDS : CAT_BREEDS
}
  return type === 'dog' ? DOG_BREEDS : CAT_BREEDS
}

export function getBreedOptions(type: PetType) {
  return getBreedsForType(type).map((breed) => ({ value: breed, label: breed }))
}
