import type { PetType } from './petTypes'
import { isCatType, isDogType } from './petTypes'

/** Well-known commercial and common diet options (CZ/EU market). */
export const DOG_FOODS = [
  // Royal Canin
  'Royal Canin Adult',
  'Royal Canin Puppy',
  'Royal Canin Mini Adult',
  'Royal Canin Medium Adult',
  'Royal Canin Maxi Adult',
  'Royal Canin Golden Retriever Adult',
  'Royal Canin Labrador Retriever Adult',
  'Royal Canin German Shepherd Adult',
  'Royal Canin Bulldog Adult',
  'Royal Canin Yorkshire Terrier Adult',
  'Royal Canin Chihuahua Adult',
  'Royal Canin Beagle Adult',
  'Royal Canin Boxer Adult',
  'Royal Canin Poodle Adult',
  'Royal Canin Dachshund Adult',
  'Royal Canin Cocker Adult',
  'Royal Canin Rottweiler Adult',
  'Royal Canin Sterilised',
  'Royal Canin Light Weight Care',
  'Royal Canin Digestive Care',
  'Royal Canin Hypoallergenic',
  'Royal Canin Gastrointestinal',
  'Royal Canin Renal',
  'Royal Canin Urinary',
  'Royal Canin Cardiac',
  'Royal Canin Hepatic',
  'Royal Canin Diabetic',
  'Royal Canin Satiety',
  'Royal Canin Anallergenic',
  'Royal Canin Veterinary Diet',
  // Hill’s
  "Hill’s Science Plan Puppy",
  "Hill’s Science Plan Adult",
  "Hill’s Science Plan Mature Adult",
  "Hill’s Science Plan Perfect Weight",
  "Hill’s Science Plan Sensitive Stomach",
  "Hill’s Science Plan Large Breed",
  "Hill’s Prescription Diet i/d",
  "Hill’s Prescription Diet c/d",
  "Hill’s Prescription Diet k/d",
  "Hill’s Prescription Diet j/d",
  "Hill’s Prescription Diet z/d",
  "Hill’s Prescription Diet Metabolic",
  "Hill’s Prescription Diet Derm Complete",
  // Purina
  'Purina Pro Plan Adult',
  'Purina Pro Plan Puppy',
  'Purina Pro Plan Sensitive Digestion',
  'Purina Pro Plan Large Athletic',
  'Purina Pro Plan Medium Adult',
  'Purina Pro Plan Small & Mini',
  'Purina Pro Plan Veterinary Diets',
  'Purina ONE Adult',
  'Purina Dog Chow',
  // Acana / Orijen
  'Acana Adult Dog',
  'Acana Puppy',
  'Acana Grasslands',
  'Acana Pacifica',
  'Acana Wild Prairie',
  'Acana Light & Fit',
  'Acana Heritage',
  'Orijen Original',
  'Orijen Puppy',
  'Orijen Six Fish',
  'Orijen Regional Red',
  'Orijen Senior',
  // Brit / Fitmin / Czech brands
  'Brit Care Adult',
  'Brit Care Puppy',
  'Brit Care Sensitive',
  'Brit Premium',
  'Brit Veterinary Diet',
  'Fitmin Medium Adult',
  'Fitmin Mini Adult',
  'Fitmin Maxi Adult',
  'Fitmin Puppy',
  'Fitmin For Life',
  'Calibra Dog Adult',
  'Calibra Dog Puppy',
  'Calibra Veterinary Diet',
  'Carnilove Adult',
  'Carnilove Puppy',
  'Carnilove True Fresh',
  'Nativia Dog',
  'Yoggies Dog',
  'Dibaq Dog',
  // Happy Dog / Josera / Bosch / Wolfsblut
  'Happy Dog Supreme',
  'Happy Dog Mini',
  'Happy Dog Sensible',
  'Josera Adult',
  'Josera Puppy',
  'Josera Light',
  'Josera Sensible',
  'Bosch Adult',
  'Bosch Puppy',
  'Wolfsblut Wild Duck',
  'Wolfsblut Blue Mountain',
  'Wolfsblut Wide Plain',
  // Farmina / Taste of the Wild / Wellness
  'Farmina N&D',
  'Farmina Cibau',
  'Taste of the Wild Pacific Stream',
  'Taste of the Wild High Prairie',
  'Taste of the Wild Appalachian Valley',
  'Wellness Core',
  'Wellness Complete Health',
  'Arden Grange Adult',
  'Eukanuba Adult',
  'Eukanuba Puppy',
  'Iams Adult',
  'Advance Adult',
  'Specific Dog',
  'Trovet Dog',
  'Virbac Veterinary HPM Dog',
  'Animonda GranCarno',
  'Animonda Vom Feinsten Dog',
  'Rinti Dog',
  'Pedigree Adult',
  'Chappi',
  'Frolic',
  // Alternative / home
  'BARF (syrová strava)',
  'Vařená strava / domácí kuchyň',
  'Smíšená strava (granule + konzervy)',
  'Veterinární dieta (dle předpisu)',
  'Jiné / vlastní krmivo',
] as const

export const CAT_FOODS = [
  // Royal Canin
  'Royal Canin Adult Cat',
  'Royal Canin Kitten',
  'Royal Canin Indoor',
  'Royal Canin Sterilised',
  'Royal Canin Maine Coon',
  'Royal Canin British Shorthair',
  'Royal Canin Persian',
  'Royal Canin Siamese',
  'Royal Canin Sensible',
  'Royal Canin Light Weight Care',
  'Royal Canin Digestive Care',
  'Royal Canin Urinary Care',
  'Royal Canin Hairball Care',
  'Royal Canin Hypoallergenic Cat',
  'Royal Canin Gastrointestinal Cat',
  'Royal Canin Renal Cat',
  'Royal Canin Urinary S/O Cat',
  'Royal Canin Diabetic Cat',
  'Royal Canin Satiety Cat',
  'Royal Canin Anallergenic Cat',
  'Royal Canin Veterinary Diet Cat',
  // Hill’s
  "Hill’s Science Plan Kitten",
  "Hill’s Science Plan Adult Cat",
  "Hill’s Science Plan Sterilised Cat",
  "Hill’s Science Plan Perfect Weight Cat",
  "Hill’s Science Plan Sensitive Stomach Cat",
  "Hill’s Prescription Diet c/d Cat",
  "Hill’s Prescription Diet k/d Cat",
  "Hill’s Prescription Diet i/d Cat",
  "Hill’s Prescription Diet z/d Cat",
  "Hill’s Prescription Diet Metabolic Cat",
  // Purina
  'Purina Pro Plan Adult Cat',
  'Purina Pro Plan Kitten',
  'Purina Pro Plan Sterilised Cat',
  'Purina Pro Plan Delicate Digestion',
  'Purina Pro Plan Veterinary Diets Cat',
  'Purina ONE Adult Cat',
  'Purina Cat Chow',
  'Gourmet Gold',
  'Gourmet Perle',
  'Felix Fantastic',
  'Felix Soup',
  'Whiskas Adult',
  'Whiskas Kitten',
  'Sheba',
  // Premium
  'Acana Cat Wild Prairie',
  'Acana Cat Pacifica',
  'Acana Cat Grasslands',
  'Orijen Cat Original',
  'Orijen Cat Six Fish',
  'Orijen Cat Regional Red',
  'Brit Care Cat',
  'Brit Premium Cat',
  'Brit Veterinary Diet Cat',
  'Fitmin Cat',
  'Calibra Cat',
  'Calibra Veterinary Diet Cat',
  'Carnilove Cat',
  'Applaws Cat',
  'Animonda Carny',
  'Animonda Vom Feinsten Cat',
  'Josera Cat',
  'Farmina N&D Cat',
  'Taste of the Wild Cat',
  'Wellness Core Cat',
  'Specific Cat',
  'Trovet Cat',
  'Virbac Veterinary HPM Cat',
  'Iams Cat',
  'Advance Cat',
  'Schesir Cat',
  'Almo Nature',
  'Cosma Cat',
  'Leonardo Cat',
  'Mac’s Cat',
  'GranataPet Cat',
  'Smilla Cat',
  'Rinti Cat',
  'Kitekat',
  // Alternative
  'BARF (syrová strava) pro kočky',
  'Vařená strava / domácí kuchyň',
  'Smíšená strava (granule + konzervy)',
  'Veterinární dieta (dle předpisu)',
  'Jiné / vlastní krmivo',
] as const

export function getFoodsForType(type: PetType): readonly string[] {
  if (isDogType(type)) return DOG_FOODS
  if (isCatType(type)) return CAT_FOODS
  return [...DOG_FOODS, ...CAT_FOODS]
}

export function getFoodOptions(type: PetType) {
  return getFoodsForType(type).map((food) => ({ value: food, label: food }))
}
