# A string used to distinguish different Supabase projects on the same host. Defaults to the
# project ID.
project_id = "loved-and-known"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.migrations]
enabled = true
schema_paths = []

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "25MiB"

[functions]
verify_jwt = true
