export {
  ONBOARDING_COMPLETED_KEY,
  SESSION_ACTIVE_KEY,
  accountNeedsOnboarding,
  addSelfAccountRole,
  completeOnboarding,
  ensureDefaultSelfAccount,
  findProfessionalProfileById,
  getMyProfilePath,
  getSelfAccount,
  isOnboardingCompleted,
  isSessionActive,
  listSelfProfessionalProfiles,
  loginSelfSession,
  logoutSelfSession,
  markOnboardingCompleted,
  resetOnboardingDemo,
  saveSelfAccount,
  setProfessionalPublicVisibility,
  upsertProfessionalIdentity,
  type CompleteOnboardingInput,
  type ProfessionalProfileDraft,
} from './session'

export {
  UI_WORKSPACE_STORAGE_KEY,
  clearUiWorkspace,
  getUiWorkspace,
  isProfessionalUiWorkspace,
  normalizeUiWorkspace,
  setUiWorkspace,
  type UiWorkspace,
} from './workspace'
