export type {
  Account,
  AccountKind,
  AccountRole,
  ConsumerRole,
  Organization,
  PetProfessionalAccess,
  ProfessionalAccessLog,
  ProfessionalAccessLogAction,
  ProfessionalAccessStatus,
  ProfessionalCredentials,
  ProfessionalPermission,
  ProfessionalProfile,
  ProfessionalPublicVisibility,
  ProfessionalType,
  ProfessionalVerificationStatus,
  PublicProfessionalProfile,
} from './types'

export {
  ACCOUNT_KINDS,
  CONSUMER_ROLES,
  KNOWN_PROFESSIONAL_TYPES,
  ORGANIZATION_PROFESSIONAL_TYPES,
  PROFESSIONAL_ACCESS_LOG_ACTIONS,
  PROFESSIONAL_ACCESS_STATUSES,
  PROFESSIONAL_PERMISSIONS,
  PROFESSIONAL_PUBLIC_VISIBILITIES,
  READ_PERMISSIONS,
  WRITE_PERMISSIONS,
} from './types'

export {
  accountHasRole,
  addAccountRole,
  isConsumerAccount,
  isConsumerRole,
  isProfessionalAccount,
  isProfessionalType,
  roleGrantsPetDataAccess,
} from './roles'

export {
  ONBOARDING_CHOICES,
  ROLE_CATALOG,
  SERVICE_SUB_ROLES,
  getOnboardingChoice,
  getRoleMeta,
  isOrganizationProfessionalType,
  listAddableRoles,
  listOnboardingOptions,
  professionalTypeFromRole,
  rolesForOnboardingChoice,
  unknownRoleIsSafe,
  type OnboardingChoice,
  type OnboardingChoiceId,
  type RoleCategory,
  type RoleMeta,
} from './catalog'

export {
  isProfessionalPermission,
  isReadPermission,
  isWritePermission,
  normalizePermissions,
  readDoesNotImplyWrite,
} from './permissions'

export {
  appendAccessLog,
  createAccessLogEntry,
  createAccessLogId,
  filterLogsForPet,
  filterLogsForProfessional,
  logsIncludeAction,
} from './audit'

export {
  activateAccess,
  assertCanAddHealthRecord,
  assertCanAddNote,
  assertCanAddVaccination,
  assertCanAddVisit,
  canProfessionalAddHealthRecord,
  canProfessionalAddNote,
  canProfessionalAddVaccination,
  canProfessionalAddVisit,
  canProfessionalViewDocuments,
  canProfessionalViewHealth,
  canProfessionalViewMedications,
  canProfessionalViewVaccinations,
  cancelPendingAccess,
  createAccessId,
  expireAccess,
  expireDueAccesses,
  findAccess,
  findOpenAccess,
  grantPetAccess,
  hasPermission,
  isAccessEffective,
  listAccessForOwner,
  listAccessForPet,
  listAccessForProfessional,
  requestProfessionalAccess,
  resolveAccessStatus,
  revokeAccess,
  updateAccessPermissions,
  type GrantPetAccessInput,
  type RequestProfessionalAccessInput,
} from './access'

export {
  activatePetProfessionalAccess,
  appendAndPersistAccessLogs,
  approvePetProfessionalAccess,
  cancelPetProfessionalAccessRequest,
  expirePetProfessionalAccess,
  getAccessListForPet,
  getAccessListForProfessional,
  getOpenAccessForPair,
  grantOwnerPetAccess,
  loadAccessState,
  reconcileExpiredPetProfessionalAccess,
  requestPetProfessionalAccess,
  revokePetProfessionalAccess,
  updatePetProfessionalAccessPermissions,
  type AccessMutationResult,
} from './accessSession'

export {
  formatPermissionList,
  PERMISSION_LABELS,
  READ_PERMISSION_OPTIONS,
  suggestedPermissionsForRole,
  WRITE_PERMISSION_OPTIONS,
} from './permissionLabels'

export {
  PROFESSIONAL_VIEW_FORBIDDEN_KEYS,
  assertProfessionalViewSafe,
  projectPetForProfessional,
  type ProfessionalPetView,
  type ProjectProfessionalPetOptions,
  type ProjectProfessionalPetResult,
} from './project'

export {
  PUBLIC_PROFESSIONAL_FORBIDDEN_KEYS,
  assertPublicProfessionalSafe,
  hasProfessionalVerifiedBadge,
  listPublicProfessionalTrustItems,
  toPublicProfessionalProfile,
  type PublicProfessionalTrustItem,
  type ToPublicProfessionalOptions,
} from './public'

export {
  PUBLIC_BREEDER_SHOWCASE_FORBIDDEN_KEYS,
  assertPublicBreederAnimalSafe,
  assertPublicBreederShowcaseSafe,
  toPublicBreederShowcase,
  type PublicBreederAnimal,
  type PublicBreederShowcase,
  type ToPublicBreederShowcaseOptions,
} from './breederShowcase'

export {
  CATALOG_ROLE_FILTERS,
  CATALOG_ROLE_SET,
  buildCatalogSearchParams,
  catalogHasActiveFilters,
  catalogRelevanceScore,
  filterPublicProfessionals,
  getCatalogRoleFilter,
  listPublicProfessionals,
  matchProfessionalCatalogQuery,
  parseCatalogSearchParams,
  queryPublicProfessionals,
  sortPublicProfessionals,
  type CatalogRoleFilter,
  type CatalogSpeciesFilter,
  type ProfessionalCatalogCriteria,
  type ProfessionalCatalogCriteriaFunctional,
} from './directory'

export {
  ACCOUNTS_STORAGE_KEY,
  ORGANIZATIONS_STORAGE_KEY,
  PET_PROFESSIONAL_ACCESS_STORAGE_KEY,
  PROFESSIONAL_ACCESS_LOGS_STORAGE_KEY,
  PROFESSIONAL_PROFILES_STORAGE_KEY,
  createProfessionalId,
  loadAccounts,
  loadOrganizations,
  loadPetProfessionalAccess,
  loadProfessionalAccessLogs,
  loadProfessionalProfiles,
  normalizeAccessLog,
  normalizeAccessLogs,
  normalizeAccount,
  normalizeAccounts,
  normalizeOrganization,
  normalizeOrganizations,
  normalizePetProfessionalAccess,
  normalizePetProfessionalAccessList,
  normalizeProfessionalProfile,
  normalizeProfessionalProfiles,
  saveAccounts,
  saveOrganizations,
  savePetProfessionalAccess,
  saveProfessionalAccessLogs,
  saveProfessionalProfiles,
} from './storage'

export {
  buildProfessionalPetCard,
  buildRecentActivity,
  canAccessProfessionalDashboard,
  canSwitchWorkspace,
  computeProfessionalDashboardStats,
  countUnreadNotificationsForAccount,
  formatActivityTime,
  getActiveSelfProfessionalProfile,
  listAvailableQuickActions,
  listProfessionalPetCards,
  listTodaysEventsForProfessional,
  loadProfessionalAccessRows,
  professionalRoleLabel,
  type ProfessionalActivityItem,
  type ProfessionalDashboardStats,
  type ProfessionalPetCardModel,
  type ProfessionalQuickAction,
} from './dashboard'
