import type { BadgeDefinition } from '../../types/badges'

/** Catalog of pet + user badges. Evaluation lives in evaluate.ts. */
export const BADGE_CATALOG: BadgeDefinition[] = [
  // ——— Pet: Milníky ———
  {
    id: 'pet_first_birthday',
    scope: 'pet',
    category: 'milestone',
    name: 'První narozeniny',
    description: 'První rok života — milník, který si zaslouží pečeť.',
    earnedFor: 'Za zaznamenané první narozeniny nebo dosažený první rok věku.',
    hint: 'Doplňte datum narození, nebo přidejte narozeniny do kalendáře.',
    icon: 'cake',
  },
  {
    id: 'pet_adoption_anniversary',
    scope: 'pet',
    category: 'milestone',
    name: 'Náš den',
    description: 'Den, kdy se cesty spojily — výročí, které zůstává.',
    earnedFor: 'Za výročí adopce zapsané v kalendáři.',
    hint: 'Přidejte do kalendáře událost Výročí adopce.',
    icon: 'home',
  },
  {
    id: 'pet_new_home',
    scope: 'pet',
    category: 'milestone',
    name: 'Našel svůj domov',
    description: 'Začátek společného příběhu pod jednou střechou.',
    earnedFor: 'Za založení profilu mazlíčka v aplikaci.',
    hint: 'Profil mazlíčka je založen — tento milník už máte.',
    icon: 'home',
  },
  {
    id: 'pet_life_milestone',
    scope: 'pet',
    category: 'milestone',
    name: 'Další rok spolu',
    description: 'Další kapitola společného života — tiše slavnostní.',
    earnedFor: 'Za významné výročí nebo milník v kalendáři.',
    hint: 'Zaznamenejte narozeniny, adopci nebo jiný životní milník.',
    icon: 'star',
  },

  // ——— Pet: Zdraví a péče ———
  {
    id: 'pet_careful_profile',
    scope: 'pet',
    category: 'health',
    name: 'Pečeť péče',
    description: 'Profil, který roste s pečlivostí — ne se soutěží.',
    earnedFor: 'Za pečlivé vedení profilu a zdravotní historie.',
    hint: 'Doplňujte údaje profilu, životní styl a zdravotní záznamy.',
    icon: 'award',
    maxLevel: 5,
    levels: [
      {
        level: 1,
        title: 'První pečeť',
        description: 'Profil mazlíčka byl založen — pečeť péče začíná.',
      },
      {
        level: 2,
        title: 'Celý portrét',
        description: 'Narození, pohlaví, hmotnost, čip a kastrace jsou vyplněné.',
      },
      {
        level: 3,
        title: 'Živý příběh',
        description: 'Profil doplňuje životní styl nebo sebehodnocení zdraví.',
      },
      {
        level: 4,
        title: 'Kronika péče',
        description: 'Kompletní profil a alespoň tři zdravotní záznamy.',
      },
      {
        level: 5,
        title: 'Plná péče',
        description: 'Profil, historie, očkování, dokument a událost v kalendáři.',
      },
    ],
  },
  {
    id: 'pet_vaccination_log',
    scope: 'pet',
    category: 'health',
    name: 'Očkování pod kontrolou',
    description: 'Klid v tom, že očkování není jen v hlavě — je zapsané.',
    earnedFor: 'Za zaznamenané očkování ve zdravotní historii.',
    hint: 'Přidejte zdravotní záznam typu Očkování.',
    icon: 'syringe',
  },
  {
    id: 'pet_vet_care',
    scope: 'pet',
    category: 'health',
    name: 'Pod dohledem',
    description: 'Péče, která má svědka — návštěva u veterináře nezůstane zapomenutá.',
    earnedFor: 'Za zaznamenanou návštěvu nebo prohlídku u veterináře.',
    hint: 'Zapište návštěvu veterináře do zdraví nebo kalendáře.',
    icon: 'stethoscope',
  },
  {
    id: 'pet_weight_tracking',
    scope: 'pet',
    category: 'health',
    name: 'Držím ho ve formě',
    description: 'Hmotnost jako jemná pozornost — ne jako hodnocení.',
    earnedFor: 'Za vyplněnou aktuální hmotnost v profilu.',
    hint: 'Doplňte aktuální hmotnost v údajích mazlíčka.',
    icon: 'scale',
  },
  {
    id: 'pet_health_history',
    scope: 'pet',
    category: 'health',
    name: 'Zdravotní kronikář',
    description: 'Historie péče psaná poctivě, záznam po záznamu.',
    earnedFor: 'Za alespoň pět zdravotních záznamů u tohoto mazlíčka.',
    hint: 'Veďte zdravotní historii — cílem je pět a více záznamů.',
    icon: 'clipboard',
  },

  // ——— Pet: Aktivity ———
  {
    id: 'pet_first_training',
    scope: 'pet',
    category: 'activity',
    name: 'První krůčky',
    description: 'První společný trénink — malý krok, velký začátek.',
    earnedFor: 'Za první trénink, agility nebo kurz v kalendáři.',
    hint: 'Naplánujte trénink, agility nebo kurz.',
    icon: 'footprints',
  },
  {
    id: 'pet_regular_activity',
    scope: 'pet',
    category: 'activity',
    name: 'V pohybu',
    description: 'Pravidelnost, která drží tělo i vztah v rytmu.',
    earnedFor: 'Za alespoň tři aktivity v kalendáři.',
    hint: 'Přidejte alespoň tři aktivity — trénink, výlet nebo péči.',
    icon: 'compass',
  },
  {
    id: 'pet_trip',
    scope: 'pet',
    category: 'activity',
    name: 'Dobrodruh',
    description: 'Společný výlet — vůně cesty a nové stopy.',
    earnedFor: 'Za zaznamenaný výlet s mazlíčkem.',
    hint: 'Přidejte do kalendáře událost Výlet.',
    icon: 'map',
  },
  {
    id: 'pet_travel',
    scope: 'pet',
    category: 'activity',
    name: 'Světoběžník',
    description: 'Cesta dál než za roh — pečeť společného putování.',
    earnedFor: 'Za událost cestování v kalendáři.',
    hint: 'Naplánujte cestování se zvířetem v kalendáři.',
    icon: 'plane',
  },

  // ——— Pet: Komunita ———
  {
    id: 'pet_first_community_post',
    scope: 'pet',
    category: 'community',
    name: 'Poprvé mezi námi',
    description: 'První sdílení příběhu s ostatními majiteli.',
    earnedFor: 'Za první komunitní příspěvek spojený s tímto mazlíčkem.',
    hint: 'Sdílejte příspěvek v komunitě a označte mazlíčka.',
    icon: 'users',
  },
  {
    id: 'pet_community_partner',
    scope: 'pet',
    category: 'community',
    name: 'Dobrý parťák',
    description: 'Když příběh rezonuje — někdo odpověděl srdcem.',
    earnedFor: 'Za reakci komunity na příspěvek s tímto mazlíčkem.',
    hint: 'Sdílejte příspěvek — lajk nebo komentář odemkne pečeť.',
    icon: 'heart',
  },

  // ——— User ———
  {
    id: 'user_careful_guardian',
    scope: 'user',
    category: 'care',
    name: 'Pečlivý páníček',
    description: 'Domácnost vedená s pozorností — profil po profilu.',
    earnedFor: 'Za pečlivou péči o profily všech mazlíčků.',
    hint: 'Doplňujte profily a zdravotní historii napříč domácností.',
    icon: 'heart',
    maxLevel: 3,
    levels: [
      {
        level: 1,
        title: 'Jeden celý portrét',
        description: 'Alespoň jeden mazlíček má kompletní profil.',
      },
      {
        level: 2,
        title: 'Celá domácnost',
        description: 'Všichni mazlíčci mají kompletní základní profil.',
      },
      {
        level: 3,
        title: 'Péče napříč srdci',
        description: 'Kompletní profily a zdravotní historie u všech.',
      },
    ],
  },
  {
    id: 'user_health_overview',
    scope: 'user',
    category: 'care',
    name: 'Klidný přehled',
    description: 'Zdraví domácnosti má řád — ne paniku.',
    earnedFor: 'Za aktivně vedené zdravotní záznamy napříč mazlíčky.',
    hint: 'Veďte zdravotní záznamy u svých mazlíčků.',
    icon: 'shield',
  },
  {
    id: 'user_calendar_ok',
    scope: 'user',
    category: 'care',
    name: 'Čas v rytmu',
    description: 'Kalendář, který drží péči i radost v jednom tempu.',
    earnedFor: 'Za naplánované události péče nebo aktivit.',
    hint: 'Přidejte alespoň jednu událost do kalendáře.',
    icon: 'calendar',
  },
  {
    id: 'user_documenter',
    scope: 'user',
    category: 'care',
    name: 'Strážce dokumentů',
    description: 'Pasy, výsledky a pojištění — pečlivě uschované.',
    earnedFor: 'Za nahrané dokumenty mazlíčků.',
    hint: 'Nahrajte pas, výsledky nebo pojištění do dokumentů.',
    icon: 'file',
  },
  {
    id: 'user_community_voice',
    scope: 'user',
    category: 'community',
    name: 'Hlas mezi svými',
    description: 'Váš příspěvek v komunitě — tichý, ale přítomný.',
    earnedFor: 'Za vlastní příspěvek v komunitě.',
    hint: 'Napište příspěvek do komunity.',
    icon: 'message',
  },
  {
    id: 'user_helps_others',
    scope: 'user',
    category: 'community',
    name: 'Pomáhá ostatním',
    description: 'Slovo podpory, které někomu ulehčí den.',
    earnedFor: 'Za komentáře, které podporují ostatní majitele.',
    hint: 'Okomentujte příspěvek někoho jiného.',
    icon: 'users',
  },
  {
    id: 'user_community_heart',
    scope: 'user',
    category: 'community',
    name: 'Komunitní srdce',
    description: 'Malé „líbí se“ — velké gesto sounáležitosti.',
    earnedFor: 'Za lajk příspěvku jiného majitele.',
    hint: 'Dejte like příspěvku v komunitě.',
    icon: 'heart',
  },
  {
    id: 'user_adventurer',
    scope: 'user',
    category: 'activity',
    name: 'Spolu v pohybu',
    description: 'Aktivity napříč domácností — život mimo gauč.',
    earnedFor: 'Za aktivity a tréninky v kalendáři.',
    hint: 'Naplánujte trénink, výlet nebo jinou aktivitu.',
    icon: 'compass',
  },
  {
    id: 'user_traveler',
    scope: 'user',
    category: 'activity',
    name: 'Cesty spolu',
    description: 'Společné cesty — blízko i dál.',
    earnedFor: 'Za cestování nebo výlet naplánovaný v kalendáři.',
    hint: 'Přidejte výlet nebo cestování do kalendáře.',
    icon: 'plane',
  },

  // ——— Secret ———
  {
    id: 'secret_night_owl',
    scope: 'user',
    category: 'secret',
    name: 'Noční strážce',
    description: 'Když svět spí a vy pečujete — tichá pečeť noci.',
    earnedFor: 'Za aktivitu v aplikaci mezi půlnocí a pátou hodinou ranní.',
    hint: '',
    secret: true,
    icon: 'moon',
  },
  {
    id: 'secret_health_archive',
    scope: 'user',
    category: 'secret',
    name: 'Archiv péče',
    description: 'Deset záznamů — kronika, která se sama odměnila.',
    earnedFor: 'Za deset zdravotních záznamů napříč domácností.',
    hint: '',
    secret: true,
    icon: 'clipboard',
  },
  {
    id: 'secret_community_helper',
    scope: 'user',
    category: 'secret',
    name: 'Tichý pomocník',
    description: 'Pomoc, která nehledá uznání — a přece ho našla.',
    earnedFor: 'Za alespoň tři komentáře pomáhající ostatním.',
    hint: '',
    secret: true,
    icon: 'sparkles',
  },
  {
    id: 'secret_evergreen',
    scope: 'pet',
    category: 'secret',
    name: 'Stálice péče',
    description: 'Dlouhodobě kompletní profil s bohatou kronikou.',
    earnedFor: 'Za dlouhodobě kompletní profil s bohatou zdravotní historií.',
    hint: '',
    secret: true,
    icon: 'award',
  },
  {
    id: 'secret_pet_traveler',
    scope: 'pet',
    category: 'secret',
    name: 'Cestovní pečeť',
    description: 'Skryté ocenění za společnou cestu světem.',
    earnedFor: 'Za cestování s mazlíčkem zaznamenané v kalendáři.',
    hint: '',
    secret: true,
    icon: 'plane',
  },
  {
    id: 'secret_adoption_day',
    scope: 'pet',
    category: 'secret',
    name: 'Den, kdy jsme se našli',
    description: 'Tajný milník dne, kdy se domov stal společným.',
    earnedFor: 'Za výročí adopce — skrytý milník společného života.',
    hint: '',
    secret: true,
    icon: 'home',
  },
]

export function getBadgeDefinition(id: string): BadgeDefinition | undefined {
  return BADGE_CATALOG.find((b) => b.id === id)
}

export const BADGE_CATEGORY_LABELS: Record<BadgeDefinition['category'], string> = {
  milestone: 'Milníky',
  health: 'Zdraví a péče',
  activity: 'Aktivity',
  community: 'Komunita',
  care: 'Péče',
  secret: 'Tajné objevy',
}
