import type { BadgeDefinition, ChallengeDefinition } from '../../types/badges'
import type { Pet } from '../../types'
import { isCatType, isDogType } from '../petTypes'

/** Experience-based peals — not profile-form checklist. */
export const BADGE_CATALOG: BadgeDefinition[] = [
  // ——— Společné životní milníky ———
  {
    id: 'life_first_birthday',
    scope: 'pet',
    category: 'milestone',
    rarity: 'common',
    name: 'První narozeniny',
    description: 'První společná oslava roku života.',
    earnedFor: 'Za zaznamenané narozeniny v kalendáři.',
    hint: 'Zaznamenejte narozeniny jako událost v kalendáři.',
    icon: 'cake',
    species: 'all',
  },
  {
    id: 'life_found_home',
    scope: 'pet',
    category: 'milestone',
    rarity: 'common',
    name: 'Našel svůj domov',
    description: 'Den, kdy se cesty spojily.',
    earnedFor: 'Za zaznamenanou adopci nebo adopční výročí.',
    hint: 'Zaznamenejte adopci / adopční výročí v kalendáři.',
    icon: 'home',
    species: 'all',
  },
  {
    id: 'life_another_year',
    scope: 'pet',
    category: 'milestone',
    rarity: 'uncommon',
    name: 'Další rok spolu',
    description: 'Další kapitola společného příběhu.',
    earnedFor: 'Za další zaznamenané narozeniny nebo kombinaci narozenin a adopce.',
    hint: 'Přidejte další narozeniny nebo výročí společného života.',
    icon: 'star',
    species: 'all',
  },

  // ——— Společné zážitky (companion) ———
  {
    id: 'exp_first_trip',
    scope: 'pet',
    category: 'companion',
    rarity: 'common',
    name: 'První výlet',
    description: 'První společná cesta za hranice všedního dne.',
    earnedFor: 'Za výlet se zadaným místem.',
    hint: 'Zaznamenejte výlet a uveďte destinaci.',
    icon: 'map',
    species: 'all',
    challengeId: 'challenge_first_trip',
  },
  {
    id: 'exp_new_place',
    scope: 'pet',
    category: 'companion',
    rarity: 'common',
    name: 'Nové místo',
    description: 'Nová stopa na mapě společných cest.',
    earnedFor: 'Za aktivitu na místě, které jste spolu ještě nenavštívili.',
    hint: 'Zaznamenejte aktivitu na nové destinaci (jiné místo než dříve).',
    icon: 'compass',
    species: 'all',
    challengeId: 'challenge_new_place',
  },
  {
    id: 'exp_little_traveler',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'Malý cestovatel',
    description: 'Tři různá místa — rostoucí mapa dobrodružství.',
    earnedFor: 'Za aktivity na alespoň třech různých místech.',
    hint: 'Navštivte a zaznamenejte aktivity na třech různých místech.',
    icon: 'globe',
    species: 'all',
  },
  {
    id: 'exp_first_training',
    scope: 'pet',
    category: 'companion',
    rarity: 'common',
    name: 'První trénink',
    description: 'První společná lekce soustředění a důvěry.',
    earnedFor: 'Za první zaznamenaný trénink nebo kurz.',
    hint: 'Zaznamenejte trénink, kurz nebo výcvik v kalendáři.',
    icon: 'footprints',
    species: 'all',
    challengeId: 'challenge_first_training',
  },
  {
    id: 'exp_first_roadtrip',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'První roadtrip',
    description: 'Kilometry spolu — cesta autem jako zážitek.',
    earnedFor: 'Za zaznamenaný roadtrip s destinací.',
    hint: 'Zaznamenejte roadtrip a uveďte destinaci.',
    icon: 'car',
    species: 'all',
  },
  {
    id: 'exp_first_abroad',
    scope: 'pet',
    category: 'companion',
    rarity: 'rare',
    name: 'První zahraniční cesta',
    description: 'Poprvé spolu za hranicemi.',
    earnedFor: 'Za zaznamenanou zahraniční cestu.',
    hint: 'Zaznamenejte zahraniční cestu v kalendáři.',
    icon: 'plane',
    species: 'all',
  },
  {
    id: 'exp_community_meetup',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'První komunitní setkání',
    description: 'Mezi svými — první společné setkání s komunitou.',
    earnedFor: 'Za zaznamenané setkání komunity.',
    hint: 'Zaznamenejte setkání komunity v kalendáři.',
    icon: 'users',
    species: 'all',
  },
  {
    id: 'exp_new_friend',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'Nový zvířecí kamarád',
    description: 'Nové přátelství na čtyřech nohách.',
    earnedFor: 'Za zaznamenané seznámení s novým zvířecím kamarádem.',
    hint: 'Zaznamenejte událost Nový zvířecí kamarád.',
    icon: 'paw',
    species: 'all',
    challengeId: 'challenge_new_environment',
  },
  {
    id: 'exp_week_five',
    scope: 'pet',
    category: 'challenge',
    rarity: 'rare',
    name: 'Týden plný zážitků',
    description: 'Pět aktivit během sedmi dní — rytmus společného života.',
    earnedFor: 'Za pět zaznamenaných aktivit v rozmezí jednoho týdne.',
    hint: 'Absolvujte a zaznamenejte pět aktivit během sedmi dní.',
    icon: 'sparkles',
    species: 'all',
    challengeId: 'challenge_five_in_week',
  },

  // ——— Pes ———
  {
    id: 'dog_first_swim',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'První plavání',
    description: 'První skok do vody — odvaha a radost.',
    earnedFor: 'Za zaznamenané plavání.',
    hint: 'Zaznamenejte plavání s místem.',
    icon: 'waves',
    species: 'dog',
  },
  {
    id: 'dog_first_agility',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'První agility',
    description: 'První sportovní dráha — tým v pohybu.',
    earnedFor: 'Za první zaznamenané agility.',
    hint: 'Zaznamenejte agility trénink nebo závod.',
    icon: 'footprints',
    species: 'dog',
  },
  {
    id: 'dog_skills',
    scope: 'pet',
    category: 'companion',
    rarity: 'rare',
    name: 'Zvládnuté povely',
    description: 'Série tréninků a zkoušek — rostoucí dovednosti.',
    earnedFor: 'Za alespoň tři tréninky/kurzy nebo úspěšnou zkoušku.',
    hint: 'Zaznamenejte tři tréninky, kurzy, nebo zkoušku.',
    icon: 'award',
    species: 'dog',
  },
  {
    id: 'dog_social',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'Mezi psy',
    description: 'Socializace s ostatními psy — jistota ve smečce.',
    earnedFor: 'Za dvě socializace nebo psí školku.',
    hint: 'Zaznamenejte socializaci nebo psí školku (alespoň dvakrát).',
    icon: 'users',
    species: 'dog',
  },

  // ——— Kočka ———
  {
    id: 'cat_first_adventure',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'Kočičí výprava',
    description: 'Výlet nebo cesta — svět za prahem.',
    earnedFor: 'Za výlet, cestování nebo roadtrip s kočkou.',
    hint: 'Zaznamenejte výlet nebo cestu s destinací.',
    icon: 'compass',
    species: 'cat',
  },
  {
    id: 'cat_harness_world',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'Svět na vodítku',
    description: 'Socializace venku — nové podněty v bezpečí.',
    earnedFor: 'Za zaznamenanou socializaci nebo kurz.',
    hint: 'Zaznamenejte socializaci nebo kurz.',
    icon: 'paw',
    species: 'cat',
  },
  {
    id: 'cat_friend',
    scope: 'pet',
    category: 'companion',
    rarity: 'uncommon',
    name: 'Kočičí přátelství',
    description: 'Nový zvířecí kamarád v kočičím tempu.',
    earnedFor: 'Za seznámení s novým zvířecím kamarádem.',
    hint: 'Zaznamenejte nového zvířecího kamaráda.',
    icon: 'heart',
    species: 'cat',
  },
  {
    id: 'cat_calm_explorer',
    scope: 'pet',
    category: 'companion',
    rarity: 'rare',
    name: 'Klidný průzkumník',
    description: 'Tři různá místa v kočičím rytmu.',
    earnedFor: 'Za aktivity na třech různých místech.',
    hint: 'Navštivte tři různá místa a zaznamenejte je.',
    icon: 'map',
    species: 'cat',
  },

  // ——— Chov (pouze Chovný profil) ———
  {
    id: 'breed_first_show',
    scope: 'pet',
    category: 'breeding',
    rarity: 'common',
    name: 'První výstava',
    description: 'První vstup do výstavního kruhu.',
    earnedFor: 'Za první výstavu se zadaným místem konání.',
    hint: 'Zaznamenejte výstavu včetně místa konání.',
    icon: 'award',
    species: 'all',
    requiresBreeding: true,
  },
  {
    id: 'breed_show_debut',
    scope: 'pet',
    category: 'breeding',
    rarity: 'uncommon',
    name: 'Výstavní debut',
    description: 'Debut s poznámkou o výsledku — skutečný start kariéry.',
    earnedFor: 'Za výstavu s místem a poznámkou o výsledku.',
    hint: 'U výstavy doplňte místo a výsledek do poznámky.',
    icon: 'star',
    species: 'all',
    requiresBreeding: true,
  },
  {
    id: 'breed_show_regular',
    scope: 'pet',
    category: 'breeding',
    rarity: 'rare',
    name: 'Výstavní stálice',
    description: 'Pět výstav — stálá přítomnost v kruhu.',
    earnedFor: 'Za pět zaznamenaných výstav.',
    hint: 'Zaznamenejte alespoň pět výstav.',
    icon: 'trophy',
    species: 'all',
    requiresBreeding: true,
  },
  {
    id: 'breed_champion',
    scope: 'pet',
    category: 'breeding',
    rarity: 'rare',
    name: 'Šampion',
    description: 'Úspěch na soutěži nebo výstavě — pečeť výkonu.',
    earnedFor: 'Za soutěžní úspěch (výsledek v poznámce) nebo tři soutěže/zkoušky.',
    hint: 'Zaznamenejte soutěž s výsledkem, nebo tři soutěže/zkoušky.',
    icon: 'trophy',
    species: 'all',
    requiresBreeding: true,
  },
  {
    id: 'breed_first_mating',
    scope: 'pet',
    category: 'breeding',
    rarity: 'uncommon',
    name: 'První krytí',
    description: 'První zaznamenané krytí v chovatelské historii.',
    earnedFor: 'Za událost krytí.',
    hint: 'Zaznamenejte krytí v kalendáři chovu.',
    icon: 'heart',
    species: 'all',
    requiresBreeding: true,
  },
  {
    id: 'breed_first_litter',
    scope: 'pet',
    category: 'breeding',
    rarity: 'rare',
    name: 'První vrh',
    description: 'První porod / vrh — milník chovatelské linie.',
    earnedFor: 'Za zaznamenaný porod / vrh.',
    hint: 'Zaznamenejte porod / vrh.',
    icon: 'home',
    species: 'all',
    requiresBreeding: true,
  },
  {
    id: 'breed_line',
    scope: 'pet',
    category: 'breeding',
    rarity: 'rare',
    name: 'Chovatelská linie',
    description: 'Krytí, vrh a kontrola — celý chovatelský příběh.',
    earnedFor: 'Za kombinaci krytí, vrhu a kontroly vrhu.',
    hint: 'Zaznamenejte krytí, porod/vrh i kontrolu vrhu.',
    icon: 'sparkles',
    species: 'all',
    requiresBreeding: true,
  },

  // ——— Tajné (6) ———
  {
    id: 'secret_explorer',
    scope: 'pet',
    category: 'secret',
    rarity: 'secret',
    name: 'Průzkumník',
    description: 'Pět různých míst — mapa, kterou jste napsali nohama.',
    earnedFor: 'Za aktivity na pěti různých místech.',
    hint: '',
    secret: true,
    icon: 'compass',
    species: 'all',
  },
  {
    id: 'secret_four_seasons',
    scope: 'pet',
    category: 'secret',
    rarity: 'secret',
    name: 'Čtyři roční období',
    description: 'Zážitek v každém ročním období.',
    earnedFor: 'Za aktivity zaznamenané na jaře, v létě, na podzim i v zimě.',
    hint: '',
    secret: true,
    icon: 'calendar',
    species: 'all',
  },
  {
    id: 'secret_everywhere',
    scope: 'pet',
    category: 'secret',
    rarity: 'secret',
    name: 'Společně všude',
    description: 'Výlet, trénink, setkání i cesta — šíře společného života.',
    earnedFor: 'Za kombinaci výletu, tréninku, komunitního setkání a cesty.',
    hint: '',
    secret: true,
    icon: 'globe',
    species: 'all',
  },
  {
    id: 'secret_still_together',
    scope: 'pet',
    category: 'secret',
    rarity: 'secret',
    name: 'Stále spolu',
    description: 'Dlouhodobá aktivita — příběh, který se píše měsíce.',
    earnedFor: 'Za aktivní profil alespoň 90 dní a opakované zážitky.',
    hint: '',
    secret: true,
    icon: 'heart',
    species: 'all',
  },
  {
    id: 'secret_unexpected_friend',
    scope: 'pet',
    category: 'secret',
    rarity: 'secret',
    name: 'Nečekané přátelství',
    description: 'Komunita a nový zvířecí kamarád — most mezi světy.',
    earnedFor: 'Za komunitní setkání a seznámení s novým zvířecím kamarádem.',
    hint: '',
    secret: true,
    icon: 'paw',
    species: 'all',
  },
  {
    id: 'secret_show_heart',
    scope: 'pet',
    category: 'secret',
    rarity: 'secret',
    name: 'Srdce kruhu',
    description: 'Výstava i vrh — chovatelský příběh v plné šíři.',
    earnedFor: 'Za výstavu a první vrh u chovného profilu.',
    hint: '',
    secret: true,
    icon: 'trophy',
    species: 'all',
    requiresBreeding: true,
  },
]

export const CHALLENGE_CATALOG: ChallengeDefinition[] = [
  {
    id: 'challenge_new_place',
    name: 'Navštivte nové místo',
    description: 'Vydejte se spolu někam, kde jste ještě nebyli.',
    instruction: 'Zaznamenejte výlet, cestu nebo aktivitu na destinaci, kterou u tohoto mazlíčka ještě nemáte.',
    badgeId: 'exp_new_place',
  },
  {
    id: 'challenge_five_in_week',
    name: 'Pět aktivit za týden',
    description: 'Naplněný týden společnými zážitky.',
    instruction: 'Zaznamenejte pět aktivit (výlet, trénink, socializace…) s daty v rozmezí sedmi dní.',
    badgeId: 'exp_week_five',
  },
  {
    id: 'challenge_new_environment',
    name: 'Nové prostředí',
    description: 'Seznamte mazlíčka s novým prostředím nebo kamarádem.',
    instruction: 'Zaznamenejte socializaci, nebo událost Nový zvířecí kamarád.',
    badgeId: 'exp_new_friend',
  },
  {
    id: 'challenge_first_trip',
    name: 'První výlet',
    description: 'Společný výlet se skutečnou destinací.',
    instruction: 'Zaznamenejte výlet a vyplňte místo / destinaci.',
    badgeId: 'exp_first_trip',
  },
  {
    id: 'challenge_first_training',
    name: 'První trénink',
    description: 'První společná lekce.',
    instruction: 'Zaznamenejte trénink, výcvik nebo kurz.',
    badgeId: 'exp_first_training',
  },
]

export function getBadgeDefinition(id: string): BadgeDefinition | undefined {
  return BADGE_CATALOG.find((b) => b.id === id)
}

export function getChallengeDefinition(id: string): ChallengeDefinition | undefined {
  return CHALLENGE_CATALOG.find((c) => c.id === id)
}

export function isBadgeApplicableToPet(def: BadgeDefinition, pet: Pet): boolean {
  const species = def.species ?? 'all'
  if (species === 'dog' && !isDogType(pet.type)) return false
  if (species === 'cat' && !isCatType(pet.type)) return false
  if (def.requiresBreeding && !pet.breedingProfile) return false
  return true
}

export function catalogForPet(pet: Pet): BadgeDefinition[] {
  return BADGE_CATALOG.filter((d) => d.scope === 'pet' && isBadgeApplicableToPet(d, pet))
}

export function challengesForPet(pet: Pet): ChallengeDefinition[] {
  return CHALLENGE_CATALOG.filter((c) => {
    const badge = getBadgeDefinition(c.badgeId)
    if (!badge) return false
    return isBadgeApplicableToPet(badge, pet)
  })
}

export const BADGE_CATEGORY_LABELS: Record<BadgeDefinition['category'], string> = {
  milestone: 'Životní milníky',
  companion: 'Společné zážitky',
  breeding: 'Chov',
  challenge: 'Výzvy',
  secret: 'Tajné objevy',
}

export const BADGE_RARITY_LABELS: Record<BadgeDefinition['rarity'], string> = {
  common: 'Běžný',
  uncommon: 'Méně častý',
  rare: 'Vzácný',
  secret: 'Tajný',
}
